"use client";

import { useState, useRef } from "react";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { v4 as uuidv4 } from "uuid";
import InputForm from "@/components/InputForm";
import LessonPlan from "@/components/LessonPlan";
import Recommendations from "@/components/Recommendations";
import type { LessonPlanData } from "@/lib/claude";
import { authHeaders } from "@/lib/auth";

function friendlyError(msg: string): string {
  if (msg.includes("API_KEY") || msg.includes("api_key") || msg.includes("401"))
    return "The app isn't configured properly yet. Please let Ted know!";
  if (msg.includes("rate") || msg.includes("429"))
    return "Too many requests — wait a moment and try again.";
  if (msg.includes("timeout") || msg.includes("504") || msg.includes("ETIMEDOUT"))
    return "That took too long. Try a simpler photo or try again.";
  if (msg.includes("image") || msg.includes("file"))
    return "There was a problem with that image. Try a different photo.";
  return "Something went wrong. Try a different photo or check your connection.";
}

interface GeneratePayload {
  file?: File;
  imageBase64?: string;
  mediaType?: string;
  sourceUrl?: string;
  notes?: string;
  caption?: string;
}

function planToEmailBody(plan: LessonPlanData, sourceUrl?: string): string {
  let body = `${plan.title}\n\n`;
  body += `${plan.overview}\n\n`;
  body += `Mess Level: ${plan.mess_level} | Time: 60 min | Cost: ${plan.total_estimated_cost}\n\n`;
  if (plan.vocabulary && plan.vocabulary.length > 0) {
    body += `Art Words: ${plan.vocabulary.join(", ")}\n\n`;
  }
  if (plan.prep_steps && plan.prep_steps.length > 0) {
    body += `--- BEFORE CLASS ---\n`;
    plan.prep_steps.forEach((s, i) => (body += `${i + 1}. ${s}\n`));
    body += `\n`;
  }
  body += `--- LEARNING OBJECTIVES ---\n`;
  plan.learning_objectives.forEach((obj) => (body += `- ${obj}\n`));
  body += `\n--- SCHEDULE ---\n`;
  plan.schedule.forEach((s) => {
    body += `${s.phase} (${s.duration_minutes} min): ${s.description}\n`;
    if (s.teacher_tip) body += `  Tip: ${s.teacher_tip}\n`;
    if (s.discussion_questions && s.discussion_questions.length > 0) {
      s.discussion_questions.forEach((q) => (body += `  - ${q}\n`));
    }
  });
  body += `\n--- MATERIALS ---\n`;
  plan.materials.forEach((m) => {
    body += `[ ] ${m.item} — ${m.quantity} (${m.estimated_cost})`;
    if (m.tip) body += ` — ${m.tip}`;
    body += `\n`;
  });
  body += `Total: ${plan.total_estimated_cost}\n`;
  body += `\n--- STEP BY STEP ---\n`;
  plan.step_by_step_instructions.forEach((s, i) => (body += `${i + 1}. ${s}\n`));
  body += `\n--- SAFETY NOTES ---\n`;
  plan.safety_notes.forEach((n) => (body += `⚠ ${n}\n`));
  body += `\n--- MODIFICATIONS ---\n`;
  body += `Easier: ${plan.modifications.easier}\n`;
  body += `Harder: ${plan.modifications.harder}\n`;
  body += `Accessibility: ${plan.modifications.accessibility}\n`;
  if (plan.parent_note) body += `\nNote for Parents: ${plan.parent_note}\n`;
  if (sourceUrl) body += `\nInspiration: ${sourceUrl}\n`;
  body += `\nGenerated by ArtSpark — Little Bay Arts & Crafts`;
  return body;
}

export default function Home() {
  const router = useRouter();
  const [generated, setGenerated] = useState<{ plan: LessonPlanData } | null>(null);
  const [sourceUrl, setSourceUrl] = useState<string | undefined>();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [savedPlanId, setSavedPlanId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const resultRef = useRef<HTMLDivElement>(null);

  /** Fire-and-forget event tracking */
  function trackEvent(planId: string, event: string) {
    fetch("/api/plans", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ plan_id: planId, event }),
    }).catch(() => {});
  }

  async function handleGenerate(input: GeneratePayload) {
    setIsGenerating(true);
    setError(null);
    setSavedPlanId(null);

    try {
      const formData = new FormData();
      if (input.file) {
        formData.set("image", input.file);
      } else if (input.imageBase64 && input.mediaType) {
        formData.set("imageBase64", input.imageBase64);
        formData.set("mediaType", input.mediaType);
      }
      if (input.notes) formData.set("notes", input.notes);
      if (input.caption) formData.set("caption", input.caption);

      const res = await fetch("/api/generate", {
        method: "POST",
        headers: authHeaders(),
        body: formData,
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Failed to generate lesson plan");
      }

      setGenerated({ plan: data.plan });
      setSourceUrl(input.sourceUrl);
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    } catch (err) {
      setGenerated(null);
      const raw = err instanceof Error ? err.message : "";
      console.error("Generate error:", raw);
      setError(friendlyError(raw));
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleSave() {
    if (!generated || isSaving) return;

    setIsSaving(true);
    setError(null);

    const id = uuidv4();

    try {
      const res = await fetch("/api/plans", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id,
          title: generated.plan.title,
          overview: generated.plan.overview,
          plan_json: JSON.stringify(generated.plan),
          source_url: sourceUrl || "",
          mess_level: generated.plan.mess_level,
          tags: [...generated.plan.tags, ...(generated.plan.season_tags || [])].join(", "),
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to save lesson plan");
      }

      setSavedPlanId(id);
      localStorage.setItem("artspark_has_saved", "1");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save lesson plan");
    } finally {
      setIsSaving(false);
    }
  }

  async function handleGenerateFromText(title: string, overview: string) {
    setIsGenerating(true);
    setError(null);
    setSavedPlanId(null);
    setSourceUrl(undefined);

    try {
      const res = await fetch("/api/generate-text", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...authHeaders() },
        body: JSON.stringify({ description: `${title}\n\n${overview}` }),
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Failed to generate lesson plan");
      }

      setGenerated({ plan: data.plan });
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    } catch (err) {
      setGenerated(null);
      const raw = err instanceof Error ? err.message : "";
      console.error("Generate-text error:", raw);
      setError(friendlyError(raw));
    } finally {
      setIsGenerating(false);
    }
  }

  function shoppingListText(plan: LessonPlanData): string {
    let text = `Shopping List: ${plan.title}\n\n`;
    plan.materials.forEach((m) => {
      text += `[ ] ${m.item} — ${m.quantity} (${m.estimated_cost})`;
      if (m.tip) text += ` — ${m.tip}`;
      text += `\n`;
    });
    text += `\nEstimated Total: ${plan.total_estimated_cost}`;
    text += `\n\nGenerated by ArtSpark — Little Bay Arts & Crafts`;
    return text;
  }

  async function doShare(title: string, text: string) {
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        await navigator.share({ title, text });
        return;
      } catch {
        // User cancelled — fall through to email
      }
    }
    const subject = encodeURIComponent(title);
    const body = encodeURIComponent(text);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  function handleSharePlan() {
    if (!generated) return;
    if (savedPlanId) trackEvent(savedPlanId, "share_plan");
    doShare(
      `Lesson Plan: ${generated.plan.title}`,
      planToEmailBody(generated.plan, sourceUrl)
    );
  }

  function handleShareList() {
    if (!generated) return;
    if (savedPlanId) trackEvent(savedPlanId, "share_list");
    doShare(
      `Shopping List: ${generated.plan.title}`,
      shoppingListText(generated.plan)
    );
  }

  function handleOpenSavedPlan() {
    if (!savedPlanId) return;
    router.push(`/plan/${savedPlanId}`);
  }

  return (
    <div className="space-y-6 pb-10">
      <section className="space-y-4 rounded-[28px] bg-white/60 p-5 shadow-sm ring-1 ring-amber-200">
        <div className="flex justify-center">
          <Image src="/logo.png" alt="Little Bay Arts & Crafts" width={96} height={96} className="h-24 w-auto rounded-full shadow-md" />
        </div>
        <div className="space-y-3 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900" style={{ fontFamily: "marker felt, comic sans ms, cursive" }}>
            ArtSpark
          </h1>
          <p className="text-xs font-medium text-amber-700" style={{ fontFamily: "marker felt, comic sans ms, cursive" }}>
            by Little Bay Arts & Crafts
          </p>
          <p className="mx-auto max-w-sm text-sm leading-6 text-gray-600">
            See a cool art project? Snap a photo and get a step-by-step
            lesson plan for your class.
          </p>
        </div>
        <div className="grid grid-cols-3 gap-2 text-center text-xs text-gray-600">
          <div className="rounded-2xl bg-white/80 px-3 py-3">
            <div className="text-lg font-semibold text-crayon-red">1</div>
            Snap a photo
          </div>
          <div className="rounded-2xl bg-white/80 px-3 py-3">
            <div className="text-lg font-semibold text-crayon-blue">2</div>
            Get your plan
          </div>
          <div className="rounded-2xl bg-white/80 px-3 py-3">
            <div className="text-lg font-semibold text-crayon-green">3</div>
            Teach it
          </div>
        </div>
      </section>

      <section className="rounded-[28px] border border-gray-200 bg-white p-5 shadow-sm">
        <div className="mb-4">
          <h2 className="text-xl font-semibold text-gray-900">
            Add your inspiration photo
          </h2>
          <p className="mt-1 text-sm text-gray-600">
            Take a photo of an art project, or paste a link from Pinterest or Instagram.
          </p>
        </div>

        <InputForm onGenerate={handleGenerate} isLoading={isGenerating} />

        {error && (
          <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        )}
      </section>

      {!generated && !isGenerating && (
        <Recommendations onSelect={handleGenerateFromText} />
      )}

      {generated ? (
        <section ref={resultRef} className="space-y-4 rounded-[28px] border border-gray-200 bg-white p-5 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <h2 className="text-xl font-semibold text-gray-900">
              Your lesson plan
            </h2>
            <Link
              href="/library"
              className="shrink-0 rounded-full bg-gray-100 px-3 py-2 text-xs font-medium text-gray-700 transition hover:bg-gray-200"
            >
              Library
            </Link>
          </div>

          {savedPlanId ? (
            <div className="rounded-2xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">
              Saved!{" "}
              <button
                type="button"
                onClick={handleOpenSavedPlan}
                className="font-semibold underline decoration-green-400 underline-offset-2"
              >
                View in library
              </button>
            </div>
          ) : null}

          <LessonPlan
            plan={generated.plan}
            sourceUrl={sourceUrl}
            onSave={handleSave}
            onSharePlan={handleSharePlan}
            onShareList={handleShareList}
            isSaved={Boolean(savedPlanId) || isSaving}
          />
        </section>
      ) : (
        <section className="rounded-[28px] border border-dashed border-gray-300 bg-gray-50 p-6 text-center">
          <p className="text-sm font-medium text-gray-700">
            Your generated lesson plan will appear here.
          </p>
          <p className="mt-1 text-sm text-gray-600">
            Start from a camera photo, a Pinterest pin, or another inspiration
            image URL.
          </p>
        </section>
      )}
    </div>
  );
}
