"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { v4 as uuidv4 } from "uuid";
import InputForm from "@/components/InputForm";
import LessonPlan from "@/components/LessonPlan";
import type { LessonPlanData } from "@/lib/claude";

interface GeneratePayload {
  file?: File;
  imageBase64?: string;
  mediaType?: string;
  sourceUrl?: string;
  notes?: string;
  caption?: string;
}

function planToEmailBody(plan: LessonPlanData, sourceUrl?: string): string {
  let body = `${plan.title}\n\n`;
  body += `${plan.overview}\n\n`;
  body += `Mess Level: ${plan.mess_level} | Time: 60 min | Cost: ${plan.total_estimated_cost}\n\n`;
  body += `--- LEARNING OBJECTIVES ---\n`;
  plan.learning_objectives.forEach((obj) => (body += `- ${obj}\n`));
  body += `\n--- SCHEDULE ---\n`;
  plan.schedule.forEach((s) => (body += `${s.phase} (${s.duration_minutes} min): ${s.description}\n`));
  body += `\n--- MATERIALS ---\n`;
  plan.materials.forEach((m) => (body += `[ ] ${m.item} - ${m.quantity} (${m.estimated_cost})\n`));
  body += `Total: ${plan.total_estimated_cost}\n`;
  body += `\n--- STEP BY STEP ---\n`;
  plan.step_by_step_instructions.forEach((s, i) => (body += `${i + 1}. ${s}\n`));
  body += `\n--- SAFETY NOTES ---\n`;
  plan.safety_notes.forEach((n) => (body += `⚠ ${n}\n`));
  body += `\n--- MODIFICATIONS ---\n`;
  body += `Easier: ${plan.modifications.easier}\n`;
  body += `Harder: ${plan.modifications.harder}\n`;
  body += `Accessibility: ${plan.modifications.accessibility}\n`;
  if (sourceUrl) body += `\nInspiration: ${sourceUrl}\n`;
  body += `\nGenerated by Little Bay Arts & Crafts`;
  return body;
}

export default function Home() {
  const router = useRouter();
  const [generated, setGenerated] = useState<{ plan: LessonPlanData } | null>(null);
  const [sourceUrl, setSourceUrl] = useState<string | undefined>();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [savedPlanId, setSavedPlanId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate(input: GeneratePayload) {
    setIsGenerating(true);
    setError(null);
    setSavedPlanId(null);

    try {
      const formData = new FormData();
      if (input.file) {
        formData.set("image", input.file);
      } else if (input.imageBase64 && input.mediaType) {
        formData.set("imageBase64", input.imageBase64);
        formData.set("mediaType", input.mediaType);
      }
      if (input.notes) formData.set("notes", input.notes);
      if (input.caption) formData.set("caption", input.caption);

      const res = await fetch("/api/generate", {
        method: "POST",
        body: formData,
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Failed to generate lesson plan");
      }

      setGenerated({ plan: data.plan });
      setSourceUrl(input.sourceUrl);
    } catch (err) {
      setGenerated(null);
      setError(
        err instanceof Error ? err.message : "Failed to generate lesson plan"
      );
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleSave() {
    if (!generated || isSaving) return;

    setIsSaving(true);
    setError(null);

    const id = uuidv4();

    try {
      const res = await fetch("/api/plans", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id,
          title: generated.plan.title,
          overview: generated.plan.overview,
          plan_json: JSON.stringify(generated.plan),
          source_url: sourceUrl || "",
          mess_level: generated.plan.mess_level,
          tags: [...generated.plan.tags, ...(generated.plan.season_tags || [])].join(", "),
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to save lesson plan");
      }

      setSavedPlanId(id);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save lesson plan");
    } finally {
      setIsSaving(false);
    }
  }

  async function handleShare() {
    if (!generated) return;
    const text = planToEmailBody(generated.plan, sourceUrl);

    // Use native share sheet on mobile (iMessage, WhatsApp, email, etc.)
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        await navigator.share({
          title: `Lesson Plan: ${generated.plan.title}`,
          text,
        });
        return;
      } catch {
        // User cancelled or share failed — fall through to email
      }
    }

    // Fallback: open email
    const subject = encodeURIComponent(`Lesson Plan: ${generated.plan.title}`);
    const body = encodeURIComponent(text);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  function handleOpenSavedPlan() {
    if (!savedPlanId) return;
    router.push(`/plan/${savedPlanId}`);
  }

  return (
    <div className="space-y-6 pb-10">
      <section className="space-y-4 rounded-[28px] bg-white/60 p-5 shadow-sm ring-1 ring-amber-200">
        <div className="flex justify-center">
          <img src="/logo.png" alt="Little Bay Arts & Crafts" className="h-24 w-24 rounded-full shadow-md" />
        </div>
        <div className="space-y-3 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900" style={{ fontFamily: "marker felt, comic sans ms, cursive" }}>
            Little Bay Arts & Crafts
          </h1>
          <p className="mx-auto max-w-sm text-sm leading-6 text-gray-600">
            Snap a photo or paste a link. Get a classroom-ready 60-minute
            lesson plan in seconds.
          </p>
        </div>
        <div className="grid grid-cols-3 gap-2 text-center text-xs text-gray-600">
          <div className="rounded-2xl bg-white/80 px-3 py-3">
            <div className="text-lg font-semibold text-crayon-red">1</div>
            Add photo or URL
          </div>
          <div className="rounded-2xl bg-white/80 px-3 py-3">
            <div className="text-lg font-semibold text-crayon-blue">2</div>
            Review lesson plan
          </div>
          <div className="rounded-2xl bg-white/80 px-3 py-3">
            <div className="text-lg font-semibold text-crayon-green">3</div>
            Save & share
          </div>
        </div>
      </section>

      <section className="rounded-[28px] border border-gray-200 bg-white p-5 shadow-sm">
        <div className="mb-4">
          <h2 className="text-xl font-semibold text-gray-900">
            Start with inspiration
          </h2>
          <p className="mt-1 text-sm text-gray-500">
            Works with uploaded images or social post URLs that expose a usable
            preview image.
          </p>
        </div>

        <InputForm onGenerate={handleGenerate} isLoading={isGenerating} />

        {error && (
          <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        )}
      </section>

      {generated ? (
        <section className="space-y-4 rounded-[28px] border border-gray-200 bg-white p-5 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">
                Your lesson plan
              </h2>
            </div>
            <Link
              href="/library"
              className="shrink-0 rounded-full bg-gray-100 px-3 py-2 text-xs font-medium text-gray-700 transition hover:bg-gray-200"
            >
              Library
            </Link>
          </div>

          {savedPlanId ? (
            <div className="rounded-2xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">
              Saved!{" "}
              <button
                type="button"
                onClick={handleOpenSavedPlan}
                className="font-semibold underline decoration-green-400 underline-offset-2"
              >
                View in library
              </button>
            </div>
          ) : null}

          <LessonPlan
            plan={generated.plan}
            sourceUrl={sourceUrl}
            onSave={handleSave}
            onShare={handleShare}
            isSaved={Boolean(savedPlanId) || isSaving}
          />
        </section>
      ) : (
        <section className="rounded-[28px] border border-dashed border-gray-300 bg-gray-50 p-6 text-center">
          <p className="text-sm font-medium text-gray-700">
            Your generated lesson plan will appear here.
          </p>
          <p className="mt-1 text-sm text-gray-500">
            Start from a camera photo, a Pinterest pin, or another inspiration
            image URL.
          </p>
        </section>
      )}
    </div>
  );
}
